# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f6d82a162c45add659b954f278366b22d782a1b2932458f27d05f830ab93ad8368be71332de8460fd330dc0d0b6ec4b67dd5b807e4e500da0abe59df5205564

test:
  secret_key_base: bb4b24d2f0600be2bdd497192c25a7c77766909bad4640e8f4be7378b0113fd12d6e38d01201da6b7308751d10d0173aeb2009e22d0effc4e16853a9da60e915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
